### ISSUE TITLE
Feature request - allow changing adapter color

### ISSUE THREAD

**Issue by kabili207** [zenaro147/PicoAdapterGB#44]
When we reach the point where we have a drop-in board replacement for the mobile adapter, users may want to have the adapter color in games reflect the actual color of their case rather than the default blue.

**Comment by zenaror** [comment]
Hey @kabili207 ! Thanks to the suggestion!

This change is not a "cosmetic thing". Almost all games that uses P2P to communicate (like Pokemon Crystal) only works if both users have the same adapter type/color. Even if you set the "unmetered" option, this is enough to make incompatible with adapters without this option.

We need to check if it will be possible to add some "fake device" into the P2P Relay Service to make all devices compatible each other.

So I can added to it, definitely! But have this little point. And it's not a code limitation... it's how the device works

**Comment by kabili207** [comment]
Well that's unfortunate. I would have figured Nintendo would have found a way around that kind of vendor lock-in, but mobile carriers did have a much bigger stranglehold on things 20 years ago

**Comment by zenaror** [comment]
> Well that's unfortunate. I would have figured Nintendo would have found a way around that kind of vendor lock-in, but mobile carriers did have a much bigger stranglehold on things 20 years ago

Yeah, definitely! 
I didn't check too much about the Relay Service... but it's basically this script here https://github.com/REONTeam/mobile-relay
probably it's possible to intercept the "adapter type command" and fake it, instead to send raw data

But as soon I finish some tests, I'll definitely add this option to change the adapter color to emulate!

**Comment by kabili207** [comment]
> Even if you set the "unmetered" option, this is enough to make incompatible with adapters without this option.

I forgot to mention it in my previous reply, but it might be a good idea to add a warning if the user changes this setting or the color. Most new users won't be aware that changing either would restrict who they can communicate with over P2P.

**Comment by zenaror** [comment]
> > Even if you set the "unmetered" option, this is enough to make incompatible with adapters without this option.
> 
> I forgot to mention it in my previous reply, but it might be a good idea to add a warning if the user changes this setting or the color. Most new users won't be aware that changing either would restrict who they can communicate with over P2P.

Definitely I will! Don't worry :)

**Comment by zenaror** [comment]
It's done @kabili207 :)
You can use the DEVICE command + color to change the adapter to emulate
for example `DEVICE=BLUE` will emulate the BLUE adapter.

Also, I added a auto-reboot after the "EXIT" command, if the device save a new config. you don't need to restart manually

Check the latest pre-release :)
https://github.com/zenaro147/PicoAdapterGB/releases/tag/beta-1.4.1
